-- models/daily_summary.sql
SELECT
    BUS_DATE,
    VENUE_CODE,
    SUM(TURNOVER_SUM) AS DAILY_TURNOVER,
    SUM(GMP_SUM) AS DAILY_REVENUE
FROM {{ source('GAME_SCHEMA', 'GAME_PERFORMANCE_DATA') }}
GROUP BY BUS_DATE, VENUE_CODE
